name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Create Virtual Environment
      run: |
        make create-env
    - name: Install dependencies
      run: |
        make install
    - name: Format with black
      run: |
        make format
    - name: Format with ruff
      run: |
        make ruff
   
    